name: Publish and Sign Container Image

on:
  # schedule:
  # - cron: '32 11 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Set lowercase github repository
        run: |
          echo "REPO_LC=${REPO,,}" >> $GITHUB_ENV
        env:
          REPO: '${{ github.repository }}'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v3.0.3'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into ghcr.io
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        id: push-step
        uses: docker/build-push-action@master
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:latest

      - name: Sign the container image
        run: cosign sign ghcr.io/${{ env.REPO_LC }}@${{ steps.push-step.outputs.digest }}

